#!/usr/bin/env bash
# =============================================================================
# sync-config.sh — Generate per-app env files from the single source of truth.
#
# Reads (later wins):
#   1. .env
#   2. .env.${DEPLOYMENT_ENVIRONMENT}   (optional per-env overrides)
#   3. .env.local                       (optional personal overrides, gitignored)
#
# Generates (with a DO NOT EDIT header):
#   backend/.env
#   frontend/.env.development
#   frontend/.env.production   (copy of dev with emulator flags forced off)
#
# Validates: warns on CHANGE_ME placeholders and missing required vars.
# =============================================================================
set -euo pipefail
shopt -s inherit_errexit 2>/dev/null || true

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

GEN_HEADER="# DO NOT EDIT — auto-generated by scripts/sync-config.sh from root .env"

log()  { printf '\033[0;34m[sync-config]\033[0m %s\n' "$*"; }
warn() { printf '\033[0;33m[sync-config] WARN:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[0;31m[sync-config] ERROR:\033[0m %s\n' "$*" >&2; exit 1; }

[[ -f .env ]] || die "Root .env not found. Copy .env.example to .env first."

# --- Load layered env into the current shell -------------------------------
# shellcheck disable=SC1090,SC1091
load_env_file() {
  local file="$1"
  [[ -f "$file" ]] || return 0
  log "Loading $file"
  set -a
  source "$file"
  set +a
}

load_env_file .env
DEPLOYMENT_ENVIRONMENT="${DEPLOYMENT_ENVIRONMENT:-development}"
load_env_file ".env.${DEPLOYMENT_ENVIRONMENT}"
load_env_file .env.local

# --- Validation -------------------------------------------------------------
REQUIRED_VARS=(
  DEPLOYMENT_ENVIRONMENT PROJECT_NAME
  POSTGRES_HOST POSTGRES_PORT POSTGRES_DB POSTGRES_USER POSTGRES_PASSWORD
  API_PORT VITE_API_URL
)
GRAPH_REQUIRED_VARS=(NEO4J_URI NEO4J_USERNAME NEO4J_PASSWORD NEO4J_DATABASE)

errors=0
for var in "${REQUIRED_VARS[@]}"; do
  if [[ -z "${!var:-}" ]]; then
    warn "Required variable '$var' is empty or unset."
    errors=$((errors + 1))
  fi
done

if [[ "${GRAPH_ENABLED:-false}" == "true" ]]; then
  for var in "${GRAPH_REQUIRED_VARS[@]}"; do
    if [[ -z "${!var:-}" ]]; then
      warn "GRAPH_ENABLED=true but '$var' is empty or unset."
      errors=$((errors + 1))
    fi
  done
fi

# CHANGE_ME placeholders: warn everywhere; hard-fail in non-development.
placeholder_hit=0
while IFS='=' read -r key _; do
  [[ "$key" =~ ^[A-Z] ]] || continue
  val="${!key:-}"
  if [[ "$val" == *CHANGE_ME* ]]; then
    warn "Placeholder value for '$key' (CHANGE_ME)."
    placeholder_hit=$((placeholder_hit + 1))
  fi
done < <(grep -E '^[A-Z][A-Z0-9_]*=' .env)

if [[ "$DEPLOYMENT_ENVIRONMENT" != "development" && "$placeholder_hit" -gt 0 ]]; then
  die "Refusing to generate config in '$DEPLOYMENT_ENVIRONMENT' with $placeholder_hit CHANGE_ME placeholder(s)."
fi
[[ "$errors" -eq 0 ]] || die "$errors validation error(s). Refusing to write partial config."

# --- Derived values ---------------------------------------------------------
DATABASE_URL="${DATABASE_URL:-postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}}"

# --- Generate backend/.env --------------------------------------------------
log "Writing backend/.env"
{
  echo "$GEN_HEADER"
  echo "DEPLOYMENT_ENVIRONMENT=${DEPLOYMENT_ENVIRONMENT}"
  echo "PROJECT_NAME=${PROJECT_NAME}"
  echo "PRODUCT_NAME=${PRODUCT_NAME:-$PROJECT_NAME}"
  echo "LOG_LEVEL=${LOG_LEVEL:-INFO}"
  echo "DATABASE_URL=${DATABASE_URL}"
  echo "POSTGRES_HOST=${POSTGRES_HOST}"
  echo "POSTGRES_PORT=${POSTGRES_PORT}"
  echo "POSTGRES_DB=${POSTGRES_DB}"
  echo "POSTGRES_USER=${POSTGRES_USER}"
  echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
  echo "DB_POOL_SIZE=${DB_POOL_SIZE:-5}"
  echo "DB_MAX_OVERFLOW=${DB_MAX_OVERFLOW:-10}"
  echo "DB_POOL_TIMEOUT=${DB_POOL_TIMEOUT:-30}"
  echo "DB_POOL_RECYCLE=${DB_POOL_RECYCLE:-1800}"
  echo "DB_POOL_PRE_PING=${DB_POOL_PRE_PING:-true}"
  echo "GCP_PROJECT_ID=${GCP_PROJECT_ID:-}"
  echo "GCP_REGION=${GCP_REGION:-us-central1}"
  echo "GCS_BUCKET=${GCS_BUCKET:-}"
  echo "GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS:-}"
  echo "AI_ENABLED=${AI_ENABLED:-false}"
  echo "AI_PROVIDER=${AI_PROVIDER:-vertex}"
  echo "GEMINI_API_KEY=${GEMINI_API_KEY:-}"
  echo "VERTEX_LOCATION=${VERTEX_LOCATION:-us-central1}"
  echo "AI_MODEL=${AI_MODEL:-gemini-1.5-flash}"
  echo "GRAPH_ENABLED=${GRAPH_ENABLED:-false}"
  echo "NEO4J_URI=${NEO4J_URI:-}"
  echo "NEO4J_USERNAME=${NEO4J_USERNAME:-neo4j}"
  echo "NEO4J_PASSWORD=${NEO4J_PASSWORD:-}"
  echo "NEO4J_DATABASE=${NEO4J_DATABASE:-neo4j}"
  echo "NEO4J_MAX_POOL_SIZE=${NEO4J_MAX_POOL_SIZE:-50}"
  echo "AUTH_ENABLED=${AUTH_ENABLED:-true}"
  echo "FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-}"
  echo "FIREBASE_AUTH_EMULATOR_HOST=${FIREBASE_AUTH_EMULATOR_HOST:-}"
  echo "TASKS_ENABLED=${TASKS_ENABLED:-false}"
  echo "CLOUD_TASKS_QUEUE=${CLOUD_TASKS_QUEUE:-}"
  echo "CLOUD_TASKS_LOCATION=${CLOUD_TASKS_LOCATION:-us-central1}"
  echo "TASKS_SERVICE_ACCOUNT=${TASKS_SERVICE_ACCOUNT:-}"
  echo "INTERNAL_BASE_URL=${INTERNAL_BASE_URL:-http://localhost:8000}"
  echo "TASKS_OIDC_AUDIENCE=${TASKS_OIDC_AUDIENCE:-}"
  echo "SCHEDULER_ENABLED=${SCHEDULER_ENABLED:-false}"
  echo "EMAIL_ENABLED=${EMAIL_ENABLED:-false}"
  echo "EMAIL_PROVIDER=${EMAIL_PROVIDER:-sendgrid}"
  echo "SENDGRID_API_KEY=${SENDGRID_API_KEY:-}"
  echo "EMAIL_FROM=${EMAIL_FROM:-no-reply@example.com}"
  echo "AI_DAILY_QUOTA_PER_TENANT=${AI_DAILY_QUOTA_PER_TENANT:-100}"
  echo "MAX_UPLOAD_BYTES=${MAX_UPLOAD_BYTES:-10485760}"
  echo "EXTRACTION_AUTOCOMMIT_THRESHOLD=${EXTRACTION_AUTOCOMMIT_THRESHOLD:-0.85}"
  echo "API_HOST=${API_HOST:-0.0.0.0}"
  echo "API_PORT=${API_PORT:-8000}"
  echo "API_VERSION=${API_VERSION:-0.1.0}"
  echo "SECRET_KEY=${SECRET_KEY:-}"
  echo "ENABLE_SWAGGER=${ENABLE_SWAGGER:-true}"
  echo "ENABLE_DETAILED_ERRORS=${ENABLE_DETAILED_ERRORS:-true}"
  echo "ENABLE_DEV_ROUTES=${ENABLE_DEV_ROUTES:-true}"
  echo "CORS_ORIGINS=${CORS_ORIGINS:-}"
  echo "CORS_ALLOW_METHODS=${CORS_ALLOW_METHODS:-GET,POST,PUT,PATCH,DELETE,OPTIONS}"
  echo "CORS_ALLOW_HEADERS=${CORS_ALLOW_HEADERS:-Authorization,Content-Type}"
  echo "FEATURE_PROJECTS=${FEATURE_PROJECTS:-true}"
  echo "FEATURE_TASKS=${FEATURE_TASKS:-true}"
  echo "MAX_REQUEST_BODY_BYTES=${MAX_REQUEST_BODY_BYTES:-10485760}"
  echo "REQUEST_TIMEOUT_SECONDS=${REQUEST_TIMEOUT_SECONDS:-30}"
  echo "RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED:-true}"
  echo "RATE_LIMIT_DEFAULT=${RATE_LIMIT_DEFAULT:-100/minute}"
  echo "BOOTSTRAP_ADMIN_EMAIL=${BOOTSTRAP_ADMIN_EMAIL:-}"
  echo "BOOTSTRAP_ADMIN_PASSWORD=${BOOTSTRAP_ADMIN_PASSWORD:-}"
  echo "BOOTSTRAP_TENANT_ID=${BOOTSTRAP_TENANT_ID:-dev-tenant}"
  echo "SENTRY_ENABLED=${SENTRY_ENABLED:-false}"
  echo "SENTRY_DSN=${SENTRY_DSN:-}"
  echo "SENTRY_TRACES_SAMPLE_RATE=${SENTRY_TRACES_SAMPLE_RATE:-0.1}"
  echo "OTEL_ENABLED=${OTEL_ENABLED:-false}"
  echo "OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-}"
  echo "OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME:-app-skeleton-backend}"
  echo "DRIFT_CHECK_ENABLED=${DRIFT_CHECK_ENABLED:-true}"
  echo "RESET_DB_ON_STARTUP=${RESET_DB_ON_STARTUP:-false}"
} > backend/.env

# --- Generate frontend/.env.development -------------------------------------
log "Writing frontend/.env.development"
{
  echo "$GEN_HEADER"
  echo "VITE_API_URL=${VITE_API_URL}"
  echo "VITE_DISABLE_AUTH=${VITE_DISABLE_AUTH:-false}"
  echo "VITE_ENABLE_ANALYTICS=${VITE_ENABLE_ANALYTICS:-false}"
  echo "VITE_GRAPH_ENABLED=${GRAPH_ENABLED:-false}"
  echo "VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY:-}"
  echo "VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN:-}"
  echo "VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID:-}"
  echo "VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET:-}"
  echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID:-}"
  echo "VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID:-}"
  echo "VITE_FIREBASE_AUTH_EMULATOR_HOST=${VITE_FIREBASE_AUTH_EMULATOR_HOST:-}"
} > frontend/.env.development

# --- Generate frontend/.env.production (emulator flags forced off) ----------
log "Writing frontend/.env.production"
{
  echo "$GEN_HEADER"
  echo "VITE_API_URL=${VITE_API_URL}"
  echo "VITE_DISABLE_AUTH=false"
  echo "VITE_ENABLE_ANALYTICS=${VITE_ENABLE_ANALYTICS:-false}"
  echo "VITE_GRAPH_ENABLED=${GRAPH_ENABLED:-false}"
  echo "VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY:-}"
  echo "VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN:-}"
  echo "VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID:-}"
  echo "VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET:-}"
  echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID:-}"
  echo "VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID:-}"
  echo "VITE_FIREBASE_AUTH_EMULATOR_HOST="
} > frontend/.env.production

if [[ "$placeholder_hit" -gt 0 ]]; then
  warn "Generated config contains $placeholder_hit CHANGE_ME placeholder(s) (allowed in development)."
fi
log "Done. Generated backend/.env, frontend/.env.development, frontend/.env.production."
