# =============================================================================
# Secret Manager. Secrets are created here (structure) but their VALUES are set
# out-of-band (scripts/create-secrets.sh or CI) so plaintext never lands in
# Terraform state or the repo. The DB password is the one exception: it is
# generated by Terraform (random_password) and stored here so Cloud Run can
# mount it.
# =============================================================================

locals {
  # Secrets whose values are managed OUTSIDE terraform (created empty).
  external_secret_ids = concat(
    [
      "${local.name_prefix}-secret-key",       # backend SECRET_KEY
      "${local.name_prefix}-firebase-project",  # FIREBASE_PROJECT_ID
    ],
    var.graph_enabled ? [
      "${local.name_prefix}-neo4j-uri",
      "${local.name_prefix}-neo4j-password",
    ] : [],
    var.ai_enabled ? [
      "${local.name_prefix}-gemini-api-key",
    ] : [],
  )
}

# --- DB password (value managed by terraform) -------------------------------
resource "google_secret_manager_secret" "db_password" {
  secret_id = "${local.name_prefix}-db-password"
  labels    = local.common_labels

  replication {
    auto {}
  }

  depends_on = [google_project_service.enabled]
}

resource "google_secret_manager_secret_version" "db_password" {
  secret      = google_secret_manager_secret.db_password.id
  secret_data = random_password.db.result
}

# --- Externally-populated secrets (created empty) ---------------------------
resource "google_secret_manager_secret" "external" {
  for_each = toset(local.external_secret_ids)

  secret_id = each.value
  labels    = local.common_labels

  replication {
    auto {}
  }

  depends_on = [google_project_service.enabled]
}
